# Generated by Django 3.2.15 on 2022-08-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='chordlink',
            field=models.URLField(default='https://www.ultimate-guitar.com/'),
        ),
    ]
