# Generated by Django 3.2.15 on 2022-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='media',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
